name: Luigi Pizzolito
markdown: kramdown
highlighter: rouge # or pygments, rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "noteforshell", "preview.png"]

quick_view_length: 150
top_categ: ["academics", "hardware", "publicspeaking", "software", "theatre", "videography"]
quick_view_length_index: 150
quick_view_length_index_noimg: 450
# sidebarpostlimit: 1
sidebarunrelpostlimit: 3
recentpostlim: 2